### ISSUE TITLE
why

### ISSUE THREAD

**Issue by darkdarcool** [RayhanADev/Hello-World-Emoticon#1]
just why

**Comment by RayhanADev** [comment]
Esoteric languages are absolutely fun ~~I'm definitely **not** trying to get more language clout on Github~~!

**Comment by darkdarcool** [comment]
~~does anyone actual get language clout on github~~ they are not fun, nor practical. Frankly i think they are a little dumb and make me want to tear out my eyeballs(**lol**)

**Comment by darkdarcool** [comment]
which one?
